In [4]:
print("hello")

hello


In [ ]:
import numpy as np
arr = np.array([1,2,3,4]) #1d matrix or vector
print(arr) 

[1 2 3 4]


In [6]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
a = [1,2,3,"hello"] #list
np.array(a) #list converted into array

array(['1', '2', '3', 'hello'], dtype='<U21')

In [ ]:
arr = np.array([[1,2,3],[4,5,6]]) #matrix
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [13]:
arr = np.ones(3)
arr

array([1., 1., 1.])

In [17]:
#linspace - do number ke beech me numbers generate kardega
arr = np.linspace(1,10,2)
arr

array([ 1., 10.])

In [ ]:
#random generation functions
np.random.rand(5) # 0 to 1 ke beech 

array([0.96697397, 0.32917834, 0.0614267 , 0.07433123, 0.22237655])

In [19]:
np.random.randn(5) #-1 to 2 ke beech

array([ 1.01383782, -1.08030395, -0.34212938, -1.58620134, -0.09635632])

In [ ]:
np.random.randint(5) #0 to 5 ke beech koi bhi number 

3

In [23]:
#array attributes
arr = np.array([[1,2,3],[4,5,6]])
np.shape(arr) #arr.shape
arr.shape

(2, 3)

In [24]:
arr.size

6

In [25]:
arr.dtype

dtype('int64')

In [26]:
#arraymethods
arr.min()

np.int64(1)

In [ ]:
arr.max()


np.int64(6)

In [29]:
arr.sum()

np.int64(21)

In [30]:
arr.mean()

np.float64(3.5)

In [31]:
arr.std()

np.float64(1.707825127659933)

In [32]:
arr.argmax()

np.int64(5)

In [33]:
arr.argmin()

np.int64(0)

In [ ]:
#sum for 2d matrix
arr = np.array([[1,2,3],[4,5,6]])
arr = np.sum(arr,axis=1) # 0 means column and 1 means row
arr

array([ 6, 15])