In [ ]:
#matrix operation
import numpy as np
arr = np.array([[1,2],[1,2]])
brr = np.array([[7,2,3],[5,2,3]])
np.dot(arr,brr) #or arr@brr

array([[1, 1],
       [2, 2]])

In [11]:
brr

array([[7, 2, 3],
       [5, 2, 3]])

In [12]:
brr.T

array([[7, 5],
       [2, 2],
       [3, 3]])

In [13]:
#advance array manipulation
arr = np.array([1,2,3,4]) #matrix stack nhi hosakti
brr = np.array([5,3,3,4])
np.vstack((arr,brr))

array([[1, 2, 3, 4],
       [5, 3, 3, 4]])

In [14]:
np.hstack((arr,brr))

array([1, 2, 3, 4, 5, 3, 3, 4])

In [15]:
np.column_stack((arr,brr))

array([[1, 5],
       [2, 3],
       [3, 3],
       [4, 4]])

In [16]:
#spiltting array
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
np.hsplit(arr,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [24]:
np.vsplit(arr,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]