In [1]:
#reshaping and resizing
import numpy as np
arr = np.arange(20)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr.reshape(5,4) #reshape

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
arr.resize(4,5) #resize
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [6]:
#slicing and indexing
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[3:6] #slicing

array([3, 4, 5])

In [8]:
arr[5] #indexing

np.int64(5)

In [12]:
#for 2d matrix 
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr[0:2,0:1] #slicing

array([[0],
       [3]])

In [15]:
arr[0,2] #indexing

np.int64(2)

In [16]:
#boolean indexing
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
bool_index = arr%2 == 0
bool_index

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [25]:
#arithmetic operations on array
a1 = np.arange(5)
a2 = np.arange(5)
a1 + a2

array([0, 2, 4, 6, 8])

In [26]:
a1 - a2

array([0, 0, 0, 0, 0])

In [27]:
a1*a2

array([ 0,  1,  4,  9, 16])

In [28]:
a1/a2

C:\Users\gagan yadav\AppData\Local\Temp\ipykernel_19552\3705041958.py:1: RuntimeWarning: invalid value encountered in divide
  a1/a2


array([nan,  1.,  1.,  1.,  1.])

In [29]:
a1%a2

C:\Users\gagan yadav\AppData\Local\Temp\ipykernel_19552\1784109576.py:1: RuntimeWarning: divide by zero encountered in remainder
  a1%a2


array([0, 0, 0, 0, 0])

In [30]:
a1 + a2

array([0, 2, 4, 6, 8])

In [ ]:
#broadcasting
lst = [1,2,3,4,5]
arr = np.array(lst)
arr + 10

array([11, 12, 13, 14, 15])

In [33]:
#shallowcopy and deepcopy
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
slice = arr[0:5] #in shallow copy , changes did in other array doesn't affect original array
slice
slice * 10
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.arange(10) # in deep copy , changes affect in original array
brr = arr
brr[0] = 10
brr
arr

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])