In [ ]:
import numpy as np

In [22]:
#valid soduku ques
s = np.array([
      [5, 3, 4, 6, 7, 8, 9, 1, 2], #in soduku evry row and column sum is 45
      [6, 7, 2, 1, 9, 5, 3, 4, 8],
      [1, 9, 8, 3, 4, 2, 5, 6, 7],

      [8, 5, 9, 7, 6, 1, 4, 2, 3],
      [4, 2, 6, 8, 5, 3, 7, 9, 1],
      [7, 1, 3, 9, 2, 4, 8, 5, 6],

      [9, 6, 1, 5, 3, 7, 2, 8, 4],
      [2, 8, 7, 4, 1, 9, 6, 3, 5],
      [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [13]:
s.sum()

np.int64(405)

In [ ]:
np.sum(s,axis=0) #columns sum

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [15]:
np.sum(s,axis=1) #rows sum

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [ ]:
#check if rows == 45 or not
c = np.sum(s,axis = 1)
c == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [20]:
c = np.sum(s,axis = 1)
for i in c:
    if i != 45:
        print("soduku is not valid")
        break
else:
    print("for rows it is valid")

for rows it is valid


In [21]:
b = np.sum(s,axis = 0)
for i in b:
    if i != 45:
        print("soduku is not valid")
        break
else:
    print("for columns it is valid")

for columns it is valid


In [23]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [ ]:
for i in range(0,9,3): #check 3 x 3 blocks of soduku 
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45
