In [ ]:
import numpy as np

In [5]:
import numpy as np
data = np.array([
    [18, 85, 78],   #student1
    [19, 92, 88],   #student2
    [17, 76, 95],   #student3
    [18, 65, 70],   #student4
    [20, 90, 85]    #student5
])

In [8]:
#get the shape of the matrix
data.shape

(5, 3)

In [9]:
#find the average age of the students
np.mean(data[:,0])

np.float64(18.4)

In [10]:
#extract math marks of all students
data[:,1:2]

array([[85],
       [92],
       [76],
       [65],
       [90]])

In [14]:
#get details of the student who score more than 90 in math
data[data[:,1] > 90]

array([[19, 92, 88]])

In [11]:
#find the highest mark of science 
np.max(data[:,2])

np.int64(95)

In [19]:
data

array([90, 97, 81, 70, 95])

In [22]:
#increase math marks of all students by 5
data = np.array([
    [18, 85, 78],   #student1
    [19, 92, 88],   #student2
    [17, 76, 95],   #student3
    [18, 65, 70],   #student4
    [20, 90, 85]    #student5
])
data[:,1] += 5
data


array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [25]:
#find how many students are younger than 19
len(data[data[:,0] < 19])

3

In [27]:
#calculate the average marks in each subject ( column-wise mean).
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [28]:
#get the data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [31]:
#replace all science marks < 75 with 0.
data[:,2][data[:,2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])